[tool.poetry]
name = "unicodeit-gtk"
version = "1.2.4"
description = "A GTK IME popup for entering symbols via (La)TeX"
authors = ["Ianis Vasilev <ianis@ivasilev.net>"]
license = "Unlicense"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
PyGObject = "^3.52.3"
unicodeit = "^0.7.5"
setproctitle = "^1.3.6"

[tool.poetry.group.dev.dependencies]
PyGObject-stubs = "^2.13.0"
mypy = "^1.17.0"
ruff = "^0.12.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
unicodeit-gtk = "unicodeit_gtk:one_shot_entry_point"
unicodeit-gtk-server = "unicodeit_gtk:server_entry_point"

[tool.ruff]
target-version = "py310"
line-length = 120

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[[tool.mypy.overrides]]
module = [
  "unicodeit.*"
]
ignore_missing_imports = true
