[tool.poetry]
name = "unicodeit-gtk"
version = "1.2.2"
description = "A GTK IME popup for entering symbols via (La)TeX"
authors = ["Ianis Vasilev <ianis@ivasilev.net>"]
license = "Unlicense"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
PyGObject = "^3.46.0"
unicodeit = "^0.7.5"
setproctitle = "^1.3.3"

[tool.poetry.group.dev.dependencies]
PyGObject-stubs = "^2.9.0"
mypy = "^1.5.1"
ruff = "^0.0.292"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py310"
line-length = 120

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[[tool.mypy.overrides]]
module = [
  "unicodeit.*"
]
ignore_missing_imports = true
