[project]
name = "unicodeit-gtk"
version = "1.2.6"
description = "A GTK IME popup for entering symbols via (La)TeX"
license = "Unlicense"
readme = "README.md"
requires-python = ">=3.10,<4.0"
authors = [
  { "name" = "Ianis Vasilev", "email" = "<ianis@ivasilev.net>" }
]

dependencies = [
  "PyGObject (>=3.54.5)",
  "unicodeit (>=0.7.5)",
  "setproctitle (>=1.3.6)",
]

[project.urls]
Repository = "https://github.com/v--/unicodeit-gtk.git"

[project.scripts]
unicodeit-gtk = "unicodeit_gtk:one_shot_entry_point"
unicodeit-gtk-server = "unicodeit_gtk:server_entry_point"

[dependency-groups]
dev = [
  "PyGObject-stubs (>=2.13.0)",
  "mypy (>=1.18.2)",
  "ruff (>=0.14.2)",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks.lint]
sequence = [
  { cmd = "ruff check $path" },
  { cmd = "mypy $path" }
]
args = [
  { name = "path", positional = true, default = "" }
]

[tool.ruff]
target-version = "py310"
line-length = 120
extend-include = ["bin/unicodeit-gtk", "bin/unicodeit-gtk-server"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.mypy]
packages = ["unicodeit_gtk"]

[[tool.mypy.overrides]]
module = [
  "unicodeit.*"
]
ignore_missing_imports = true
